name: Test a pen he does

on:
  push:
    branches:
      - main
    schedule:
      # Adjust refresh schedule here. By default, it runs once per day.
      # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
      # Recommended tool: https://crontab.guru/
      # Run it every 6 hours
      - cron: "* */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: bash -c "echo $RANDOM >> ./index.html"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          user_name: 'robot2051'
          user_email: 'pt-robot@ebfe.pw'
